//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviss
    {
        public int ID { get; set; }
        public Nullable<int> ID_RDV { get; set; }
        public Nullable<int> NOTE_FACIL { get; set; }
        public Nullable<int> NOTE_ACCUEIL { get; set; }
        public Nullable<int> NOTE_PROMPATITUDE { get; set; }
        public Nullable<int> NOTE_DIAG { get; set; }
        public Nullable<int> NOTE_RECOM { get; set; }
    }
}
